id: green_taxi_to_postgres
namespace: company.team

concurrency:
  limit: 1

inputs:
  - id: taxi
    type: SELECT
    displayName: Select taxi type
    values: [ yellow, green ]
    defaults: yellow

variables:
  target_date: "{{ (trigger.date ?? '2021-01-01') | date('yyyy-MM') }}"
  file_name: "{{ inputs.taxi }}_tripdata_{{ render(vars.target_date) }}.csv"
  table: "public.{{ inputs.taxi }}_tripdata"
  staging_table: "public.{{ inputs.taxi }}_tripdata_staging"

tasks:
  - id: extract
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.csv"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - wget -qO- https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{{ inputs.taxi }}/{{ render(vars.file_name) }}.gz | gunzip > {{ render(vars.file_name) }}

  - id: if_yellow_taxi
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.taxi == 'yellow' }}"
    then:
      - id: yellow_create_table
        type: io.kestra.plugin.jdbc.postgresql.Queries
        sql: |
          CREATE TABLE IF NOT EXISTS {{ render(vars.table) }} (
              unique_row_id text PRIMARY KEY, filename text, VendorID text, tpep_pickup_datetime timestamp, tpep_dropoff_datetime timestamp, passenger_count integer, trip_distance double precision, RatecodeID text, store_and_fwd_flag text, PULocationID text, DOLocationID text, payment_type integer, fare_amount double precision, extra double precision, mta_tax double precision, tip_amount double precision, tolls_amount double precision, improvement_surcharge double precision, total_amount double precision, congestion_surcharge double precision
          );

      - id: yellow_staging_and_load
        type: io.kestra.plugin.jdbc.postgresql.Queries
        sql: |
          DROP TABLE IF EXISTS {{ render(vars.staging_table) }};
          CREATE TABLE {{ render(vars.staging_table) }} (
              unique_row_id text,
              filename text, 
              VendorID text, 
              tpep_pickup_datetime timestamp, 
              tpep_dropoff_datetime timestamp, 
              passenger_count integer, 
              trip_distance double precision, 
              RatecodeID text, 
              store_and_fwd_flag text, 
              PULocationID text, 
              DOLocationID text, 
              payment_type integer, 
              fare_amount double precision, 
              extra double precision, 
              mta_tax double precision, 
              tip_amount double precision, 
              tolls_amount double precision, 
              improvement_surcharge double precision, 
              total_amount double precision, 
              congestion_surcharge double precision
          );

      - id: yellow_copy_in
        type: io.kestra.plugin.jdbc.postgresql.CopyIn
        from: "{{ outputs.extract.outputFiles[render(vars.file_name)] }}"
        table: "{{ render(vars.staging_table) }}"
        header: true
        format: CSV
        columns: [ VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge ]

      - id: yellow_upsert
        type: io.kestra.plugin.jdbc.postgresql.Queries
        sql: |
          UPDATE {{ render(vars.staging_table) }} SET 
            filename = '{{ render(vars.file_name) }}',
            unique_row_id = md5(COALESCE(VendorID, '') || COALESCE(tpep_pickup_datetime::text, '') || COALESCE(PULocationID, ''));

          MERGE INTO {{ render(vars.table) }} T 
          USING (SELECT DISTINCT ON (unique_row_id) * FROM {{ render(vars.staging_table) }}) S 
          ON T.unique_row_id = S.unique_row_id
          WHEN NOT MATCHED THEN INSERT (unique_row_id, filename, VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge)
          VALUES (S.unique_row_id, S.filename, S.VendorID, S.tpep_pickup_datetime, S.tpep_dropoff_datetime, S.passenger_count, S.trip_distance, S.RatecodeID, S.store_and_fwd_flag, S.PULocationID, S.DOLocationID, S.payment_type, S.fare_amount, S.extra, S.mta_tax, S.tip_amount, S.tolls_amount, S.improvement_surcharge, S.total_amount, S.congestion_surcharge);

  - id: if_green_taxi
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.taxi == 'green' }}"
    then:
      - id: green_create_table
        type: io.kestra.plugin.jdbc.postgresql.Queries
        sql: |
          CREATE TABLE IF NOT EXISTS {{ render(vars.table) }} (
              unique_row_id text PRIMARY KEY, filename text, VendorID text, lpep_pickup_datetime timestamp, lpep_dropoff_datetime timestamp, store_and_fwd_flag text, RatecodeID text, PULocationID text, DOLocationID text, passenger_count integer, trip_distance double precision, fare_amount double precision, extra double precision, mta_tax double precision, tip_amount double precision, tolls_amount double precision, ehail_fee double precision, improvement_surcharge double precision, total_amount double precision, payment_type integer, trip_type integer, congestion_surcharge double precision
          );

      - id: green_staging_and_load
        type: io.kestra.plugin.jdbc.postgresql.Queries
        sql: |
          DROP TABLE IF EXISTS {{ render(vars.staging_table) }};
          CREATE TABLE {{ render(vars.staging_table) }} (
              unique_row_id text,
              filename text, 
              VendorID text, 
              lpep_pickup_datetime timestamp, 
              lpep_dropoff_datetime timestamp, 
              store_and_fwd_flag text, 
              RatecodeID text, 
              PULocationID text, 
              DOLocationID text, 
              passenger_count integer, 
              trip_distance double precision, 
              fare_amount double precision, 
              extra double precision, 
              mta_tax double precision, 
              tip_amount double precision, 
              tolls_amount double precision, 
              ehail_fee double precision, 
              improvement_surcharge double precision, 
              total_amount double precision, 
              payment_type integer, 
              trip_type integer, 
              congestion_surcharge double precision
          );

      - id: green_copy_in
        type: io.kestra.plugin.jdbc.postgresql.CopyIn
        from: "{{ outputs.extract.outputFiles[render(vars.file_name)] }}"
        table: "{{ render(vars.staging_table) }}"
        header: true
        format: CSV
        columns: [ VendorID, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, RatecodeID, PULocationID, DOLocationID, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge ]

      - id: green_upsert
        type: io.kestra.plugin.jdbc.postgresql.Queries
        sql: |
          UPDATE {{ render(vars.staging_table) }} SET 
            filename = '{{ render(vars.file_name) }}',
            unique_row_id = md5(COALESCE(VendorID, '') || COALESCE(lpep_pickup_datetime::text, '') || COALESCE(PULocationID, ''));

          MERGE INTO {{ render(vars.table) }} T 
          USING (SELECT DISTINCT ON (unique_row_id) * FROM {{ render(vars.staging_table) }}) S 
          ON T.unique_row_id = S.unique_row_id
          WHEN NOT MATCHED THEN INSERT (unique_row_id, filename, VendorID, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, RatecodeID, PULocationID, DOLocationID, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge)
          VALUES (S.unique_row_id, S.filename, S.VendorID, S.lpep_pickup_datetime, S.lpep_dropoff_datetime, S.store_and_fwd_flag, S.RatecodeID, S.PULocationID, S.DOLocationID, S.passenger_count, S.trip_distance, S.fare_amount, S.extra, S.mta_tax, S.tip_amount, S.tolls_amount, S.ehail_fee, S.improvement_surcharge, S.total_amount, S.payment_type, S.trip_type, S.congestion_surcharge);

pluginDefaults:
  - type: io.kestra.plugin.jdbc.postgresql
    values:
      url: jdbc:postgresql://pgdatabase:5432/ny_taxi
      username: root
      password: "secure-taxi-root"

triggers:
  - id: taxi_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"